### PR TITLE
Jobs: Introduce Job Name filter

### PR DESCRIPTION
**Pull request by vibhoothi**
This commit introduces option to filter based on job_name,
Right now can search for job and list in the main list of jobs for selection.
Also enable to select multiple jobs

Screenshots:
image
image
image
image

### CODE REVIEW

**Comment by vibhoothi** [comment]
@tdaede ^^

**Comment by tdaede** [comment]
This seems good! Would it also make sense for this to match substrings? e.g. find all jobs containing "directopt".

**Comment by vibhoothi** [comment]
@tdaede Yes, it works, also case-insensitive ATM, I did not do work on pattern matching, but it can match substring, and also case in-sensitive.

image
image

**Comment by vibhoothi** [comment]
@tdaede can we land this

**Review by tdaede — APPROVED** [review]

**Pull request merged**
