### PR TITLE
awcy: replace all spaces in run name with _

### LINKED ISSUE #27: Spaces in test names don't work

### PR DESCRIPTION
**Pull request by tmatth**
Before this change, only the first was being replaced. Fixes #27 and #197.

### CODE REVIEW

**Comment by tmatth** [comment]
Marked as draft as I haven't had the chance to test yet, if anyone can easily build+run+validate the fix it'd be appreciated.

**Review by vibhoothi — APPROVED** [review]
Thanks for the patch,


Tested locally in VLC12, 

image
image
image


It works :)

**Comment by tmatth** [comment]
> Thanks for the patch,
> 
> Tested locally in VLC12,
> 
> image image image
> 
> It works :)
> 
> Edit: http://vlc12.xiph.osuosl.org:3000/?job=testing_locally_a_broken_run_without_commit Can test here,

Thanks for testing, I pushed a minor tweak so that any whitespace will get replaced (not just space characters).

**Review by vibhoothi — APPROVED** [review]
image

New version works well too,
LGTM

**Pull request merged**
