### PR TITLE
Update Dockerfile to build dav1d

### PR DESCRIPTION
**Pull request by rzumer**
This adds support for decoding rav1e output with dav1d from https://github.com/xiph/rd_tool/pull/51.

### CODE REVIEW

**Comment by tdaede** [comment]
I'm now hitting permission errors because Cargo is trying to use /usr/local/cargo, which isn't writable. I see you've already 777'd it but that doesn't seem to be enough.

It may also make sense to not run as root inside the container....

**Comment by tdaede** [comment]
The new Ubuntu seems to break scp copying files back, due to this:

https://bugzilla.redhat.com/show_bug.cgi?id=1722229

**Comment by rzumer** [comment]
That's supposed to be solved by https://github.com/xiph/awcy/commit/7ed853ac16c0d3e064f3b2eddb9f1dabfe1a4e00, if not then it needs to be updated I guess.

**Comment by tdaede** [comment]
I think it's an unrelated issue. The chmod 777 doesn't affect directories and files that are created later.

I think what we should really do is set $HOME/$CARGO_HOME/$RUSTUP_HOME correctly for the runtime user. I'll see if I can do that.

**Comment by rzumer** [comment]
I'm not sure what "chmod 777" you are referring to, I set +w to the registry directory for users in a different PR, is that what you are referring to?

**Pull request merged**
