### PR TITLE
Update the AOM Analyzer URL

### PR DESCRIPTION
**Pull request by rzumer**

### CODE REVIEW

**Review by tmatth — CHANGES_REQUESTED** [review]
The decoder URLs all 404.

**Comment by rzumer** [comment]
The decoder is missing but the root path (https://media.xiph.org/analyzer/) exists and inspect.js is there. I don't know where to find the decoder binary or if I even have access to this directory to add it if I find it. Either way the PR will probably not change once that is solved.

**Comment by tdaede** [comment]
inspect.js == decoder.js I believe

**Comment by rzumer** [comment]
Oh I see, thanks for clarifying.

**Review by tmatth — APPROVED** [review]

**Pull request merged**
